
if __name__ == '__main__':
    print("boyi")
    print("hkhaldlkkka")
    print("beoyi")
    print("test")
    print("test2")
    print("test2")
    print("test3")
    print("test")
    print("test")
    print("test")
    print("test")
    print("test")
    print("test")
    print("test2")
    print("test3")
    print("test")
    print("boyi")
    print("test")
    print("test")
    print('test2')
    print("boyi")
